# Supported: GCC, CLANG, ICC
TOOLCHAIN ?= CLANG
# Supported CRS, SCS, CCRS
MTX_FMT ?= CRS
ENABLE_MPI ?= false
ENABLE_OPENMP ?= false
PRECISION ?= 2 # 1 for float, 2 for double

#Feature options
OPTIONS +=  -DARRAY_ALIGNMENT=64
OPTIONS +=  -DOMP_SCHEDULE=static
#OPTIONS +=  -DVERBOSE
#OPTIONS +=  -DVERBOSE_AFFINITY
#OPTIONS +=  -DVERBOSE_DATASIZE
#OPTIONS +=  -DVERBOSE_TIMER
